/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.maciej.szczypta.maciejszczypta;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author gromm
 */
public class Zadanie extends javax.swing.JFrame {

    /**
     * Creates new form Zadanie
     */
    public Zadanie() {
        initComponents();
        
        String Image = System.getProperty("user.dir");
        Image = Image + "\\src\\main\\java\\pl\\maciej\\szczypta\\maciejszczypta\\resources\\logo.png";
        System.out.println("Lokacja loga " + Image);
        
        ImageIcon icona = new ImageIcon(Image);
        ms_jLabelImage.setIcon(icona);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        ms_jLabel1 = new javax.swing.JLabel();
        ms_jRadioButtonYES = new javax.swing.JRadioButton();
        ms_jRadioButtonNO = new javax.swing.JRadioButton();
        ms_jLabelImage = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        ms_jMenuPlik = new javax.swing.JMenu();
        ms_jMenuItemSave = new javax.swing.JMenuItem();
        ms_jMenuItemLoad = new javax.swing.JMenuItem();
        ms_jMenuItemClose = new javax.swing.JMenuItem();
        ms_jMenuEdit = new javax.swing.JMenu();
        ms_jMenuItemFont = new javax.swing.JMenuItem();
        ms_jMenuItemBG = new javax.swing.JMenuItem();
        ms_jMenuOprog = new javax.swing.JMenu();
        ms_jMenuItemAbout = new javax.swing.JMenuItem();
        ms_jMenuItemHelp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Zadanie");

        ms_jLabel1.setText("NOWY PROGRAM!!!!");

        buttonGroup1.add(ms_jRadioButtonYES);
        ms_jRadioButtonYES.setText("TAAAAK");

        buttonGroup1.add(ms_jRadioButtonNO);
        ms_jRadioButtonNO.setText("NIE?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ms_jRadioButtonNO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                        .addComponent(ms_jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ms_jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ms_jRadioButtonYES))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(ms_jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ms_jRadioButtonYES)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ms_jRadioButtonNO)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(ms_jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ms_jMenuPlik.setText("Plik");

        ms_jMenuItemSave.setText("zapisz");
        ms_jMenuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jMenuItemSaveActionPerformed(evt);
            }
        });
        ms_jMenuPlik.add(ms_jMenuItemSave);

        ms_jMenuItemLoad.setText("wczytaj");
        ms_jMenuItemLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jMenuItemLoadActionPerformed(evt);
            }
        });
        ms_jMenuPlik.add(ms_jMenuItemLoad);

        ms_jMenuItemClose.setText("zamknij");
        ms_jMenuItemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jMenuItemCloseActionPerformed(evt);
            }
        });
        ms_jMenuPlik.add(ms_jMenuItemClose);

        jMenuBar1.add(ms_jMenuPlik);

        ms_jMenuEdit.setText("Edycja");

        ms_jMenuItemFont.setText("zmien czcionke");
        ms_jMenuEdit.add(ms_jMenuItemFont);

        ms_jMenuItemBG.setText("zmien tlo");
        ms_jMenuEdit.add(ms_jMenuItemBG);

        jMenuBar1.add(ms_jMenuEdit);

        ms_jMenuOprog.setText("O programie");

        ms_jMenuItemAbout.setText("o programie");
        ms_jMenuOprog.add(ms_jMenuItemAbout);

        ms_jMenuItemHelp.setText("help");
        ms_jMenuOprog.add(ms_jMenuItemHelp);

        jMenuBar1.add(ms_jMenuOprog);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ms_jMenuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jMenuItemSaveActionPerformed
        Save();
    }//GEN-LAST:event_ms_jMenuItemSaveActionPerformed

    private void ms_jMenuItemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jMenuItemCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ms_jMenuItemCloseActionPerformed

    private void ms_jMenuItemLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jMenuItemLoadActionPerformed
        System.out.println("Load nie dziala");
        Load();
    }//GEN-LAST:event_ms_jMenuItemLoadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Zadanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Zadanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Zadanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Zadanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Zadanie().setVisible(true);
            }
        });
    }
    
    private void Save(){
        String Directory = System.getProperty("user.dir");
        System.out.println("Lokacja " + Directory);
        String button;
        
        if(ms_jRadioButtonYES.isSelected()){
            button ="tak";
        }else if(ms_jRadioButtonNO.isSelected()){
            button = "nie";
        }else{
            button = "nico";
        }
               
        
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(Directory));
        
        try {
            FileWriter writer = new FileWriter("Setting.txt", true);
            writer.write(button);
            
            writer.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private void Load(){
        try {
            FileReader reader = new FileReader("Setting.txt");
            
            
            reader.close();
 
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ms_jLabel1;
    private javax.swing.JLabel ms_jLabelImage;
    private javax.swing.JMenu ms_jMenuEdit;
    private javax.swing.JMenuItem ms_jMenuItemAbout;
    private javax.swing.JMenuItem ms_jMenuItemBG;
    private javax.swing.JMenuItem ms_jMenuItemClose;
    private javax.swing.JMenuItem ms_jMenuItemFont;
    private javax.swing.JMenuItem ms_jMenuItemHelp;
    private javax.swing.JMenuItem ms_jMenuItemLoad;
    private javax.swing.JMenuItem ms_jMenuItemSave;
    private javax.swing.JMenu ms_jMenuOprog;
    private javax.swing.JMenu ms_jMenuPlik;
    private javax.swing.JRadioButton ms_jRadioButtonNO;
    private javax.swing.JRadioButton ms_jRadioButtonYES;
    // End of variables declaration//GEN-END:variables
}
